Various enhancements and fixes - APIs based features
elastic/ece-support-diagnostics pull request #77
Opened 2021-07-24 23:44 UTC by jguay

There are a few changes if any of you would like to review we can discuss @Leaf-Lin @bsturg @kiju98 @jakommo @111andre111 @seang-es @geekpete @BobBlank12 @jstrassb @robin13 

I have not updated README.MD and can send a separate PR to merge when we are ready to release as there are some breaking changes like renaming of script file, removal of option `-a` and `-c`

Here are the issues affected 

Close https://github.com/elastic/ece-support-diagnostics/issues/5 - function get_mntr_ZK included

Close https://github.com/elastic/ece-support-diagnostics/issues/6 - cleanup and exit on invalid credentials

Close https://github.com/elastic/ece-support-diagnostics/issues/14 - preserve timestamp of log files 

Close https://github.com/elastic/ece-support-diagnostics/issues/15 - Expose a setting to filter out old logs (from already existing default of 72 hours)

Close https://github.com/elastic/ece-support-diagnostics/issues/20 - error or guess on invalid storage location

Close https://github.com/elastic/ece-support-diagnostics/issues/22 - It seems diagnostics.sh doesn't work well with another locale such like 'LC_ALL =ja_JP.UTF-8'

Close https://github.com/elastic/ece-support-diagnostics/issues/28 - collect ECE license

Close https://github.com/elastic/ece-support-diagnostics/issues/43 - Collect instance configuration

Close https://github.com/elastic/ece-support-diagnostics/issues/50 - [Enhancement Request] Allow for a password prompt using an empty -p flag

Close https://github.com/elastic/ece-support-diagnostics/issues/59 - change parameter long name from `--user` to `--username` to match documentation

Close https://github.com/elastic/ece-support-diagnostics/issues/71 - rename ece-diagnostics.sh

Close https://github.com/elastic/ece-support-diagnostics/issues/72 - store deployment info in elastic folder (do that by default on all deployment, also added a comma-separated arg `-de|--deployment` to get plan activity logs from deployment(s))

---

Other points to mention matching no current issue : 
- The main change is we will run APIs we by default in the fashion of ES diagnostics, I added a few I thought might be useful even if there was no issue and it should be simple to add/remove API calls with a min(default 2.0.0)/max version, the structure of folders is hardcoded to `elastic` subfolder in different subfolders like `platform`, `deployments`, `stacks`, `users`, `v0containersets`, some with subfolders... This could be changed before release
- removed `-a` (collected by default) 
- removed `-c` (`-de` will get the same info but not limited to ES cluster - there is no filtering on logs though so ECE bundle will be larger when run from an allocator)
- I added a feature so output of running the script is also sent in a log file included in the bundle, including with ece-diag version (`2.0.0` because there are breaking changes)

2021-07-26 10:11 UTC, jguay commented
Note for later - I think `snapshot_repositories.json` might be one we will want to exclude from the collected APIs prior to release as it may contain keys - or potentially filter out any line with key

2021-08-05 09:02 UTC, 111andre111 requested changes
Left my comments that should be addresed in my opinion.

2021-08-05 09:02 UTC, 111andre111 commented on src/ece-diagnostics.sh
> +        request="curl -s -S -X$method -u $user:$password $protocolrequest://$ece_host:$ece_port$path -o $output_file"
I think if we already restructure towards a version 2 diagnostics, we should offer options as well like for self signed certificate environments offer -k option for ignoring certificate validation of offer the root certificate.
Jakob offered some good ideas here:
https://github.com/elastic/ece-support-diagnostics/issues/55#issuecomment-651160067

2021-08-05 09:02 UTC, 111andre111 commented on src/ece-diagnostics.sh
> +        do_http_request GET "$protocol" /api/v1//platform "$ece_port" "" "$elastic_folder"/platform/platform.json
it is only cosmetical, however why there are lots of calls with 2 backslashes? /api/v1//....
Can you please correct them towards /api/v1/... with only 1 backslash?

2021-08-05 09:17 UTC, jguay commented on src/ece-diagnostics.sh
> +            return -1
Thank you - you are right return should only work for 0 to 255, I'll correct this

2021-08-05 09:19 UTC, jguay commented on src/ece-diagnostics.sh
> +        request="curl -s -S -X$method -u $user:$password $protocolrequest://$ece_host:$ece_port$path -o $output_file"
I think this discussion is not coming from PR (I am not adding feature for -k or provide CA cert to curl in this PR), I was edging towards -k by default and port 12443 here but ended up not working on this - a bit more secured than unencrypted traffic, I could add a commit for this (adding options for insecure and passing ca file needs a bit more work so maybe it would deserve another PR later)

2021-08-05 09:22 UTC, 111andre111 commented on src/ece-diagnostics.sh
> +        request="curl -s -S -X$method -u $user:$password $protocolrequest://$ece_host:$ece_port$path -o $output_file"
Sure absolutely, I thought it might be worth raising due to the fact there are so many changes.

2021-08-05 09:24 UTC, jguay commented on src/ece-diagnostics.sh
> +                bash -c "${DIR}/displaySrvCertExpiration -h ${ece_host} -p 12443 2>/dev/null" > "$elastic_folder"/certs/coordinator_12443.json
I didn't know we could customise coordinator port (I have not seen that but some customers have a LB in front of coordinators with different port), in that case the file will return no cert information currently... I am not sure if this is fixable although I could default to port provided by user only when `-y https` is used, does this make sense as a fix?

2021-08-05 09:39 UTC, jguay commented on src/ece-diagnostics.sh
> +        do_http_request GET "$protocol" /api/v1//platform "$ece_port" "" "$elastic_folder"/platform/platform.json
Good catch, I have always used these APIs as this is how they come in postman when importing swagger.json
I have tested in 2.0.0 and `/platform` (or equivalent `/api/v1//platform`), `/api/v1/platform` work so I have added a commit to fix that thank you

2021-08-05 09:48 UTC, 111andre111 commented on src/ece-diagnostics.sh
> +        do_http_request GET "$protocol" /api/v1//platform "$ece_port" "" "$elastic_folder"/platform/platform.json
Yeah, I know. I have seen this in postman too already. Maybe a good point in time to address that in upstream...

2021-08-05 09:52 UTC, 111andre111 commented on src/ece-diagnostics.sh
> +                bash -c "${DIR}/displaySrvCertExpiration -h ${ece_host} -p 12443 2>/dev/null" > "$elastic_folder"/certs/coordinator_12443.json
Sorry if I don't understand.
We offer parameter `-x` for providing customer port that sets variable `ece_port` in line 721...

2021-08-05 10:03 UTC, 111andre111 commented on src/ece-diagnostics.sh
> +            return -1
Afaik like I posted already a negative value should be possible as well with the mentioned `--` because return values are generally modulo 256...

2021-08-05 10:05 UTC, jguay commented on src/ece-diagnostics.sh
> +        request="curl -s -S -X$method -u $user:$password $protocolrequest://$ece_host:$ece_port$path -o $output_file"
cool thanks I'll leave that maybe for 2.0.1, it's a few changes to do it right so maybe we can add it later

2021-08-05 10:06 UTC, jguay commented on src/ece-diagnostics.sh
> +                bash -c "${DIR}/displaySrvCertExpiration -h ${ece_host} -p 12443 2>/dev/null" > "$elastic_folder"/certs/coordinator_12443.json
cool thanks I'll leave that for later then

2021-08-05 10:11 UTC, jguay commented on src/ece-diagnostics.sh
> +                bash -c "${DIR}/displaySrvCertExpiration -h ${ece_host} -p 12443 2>/dev/null" > "$elastic_folder"/certs/coordinator_12443.json
Thank you I will now default to 12443 unless `-y` is set to `https` in which case reuse the port provided

2021-08-06 08:55 UTC, 111andre111 commented
Hmmm, interesting.
I still wanted to do a sanity check with the vercomp test.
Interesting here is, that with e.g. version 2.2.1
following command:
`./ece-diagnostics.sh -u admin -p <pw>`
resulted in following api call entries:
```
/api/v1/platform/infrastructure/constructors
/api/v1/platform/infrastructure/proxies
/api/v1/platform/infrastructure/runners
/api/v1/platform/configuration/instances?show_deleted=false
/api/v1/platform/configuration/templates/deployments?show_instance_configurations=false
/api/v1/platform/configuration/store
/api/v1/platform/configuration/security/realms
/api/v1/stack/versions
/api/v0/regions/ece-region/container-sets/allocators
/api/v0/regions/ece-region/container-sets/proxies
/api/v0/regions/ece-region/container-sets/zookeeper-servers
```
however with additional system and docker flags, the api calls are much less, which seems to me that something is not working appropriately. With a parallel test under 2.9 everything seemed to work as expected:
`./ece-diagnostics.sh -s -d -u admin -p <pw>`
API call result was:
```
/api/v1/platform
```
So a lot less API calls were executed and it seems in the case vercomp kicks in and additionally flags like -s or -d are set, api calls don't work.



Another topic that I uncovered is, do we maybe default to a root or admin user?
because command:
`./ece-diagnostics.sh -p <pw>`
didn't get any api calls at all.
Is this intentional?

2021-08-06 09:58 UTC, 111andre111 commented
Apart from that LGTM

2021-08-06 09:59 UTC, 111andre111 approved these changes
LGTM

2021-08-06 11:34 UTC, merged